### ISSUE TITLE
Complete ADE deployment removal and fix infrastructure deployment workflow

### ISSUE THREAD

**Issue by JFolberth** [JFolberth/ai-in-a-box#100]
## 🎯 Objective

Complete the removal of Azure Deployment Environment (ADE) deployment steps from CI/CD and fix the infrastructure deployment workflow to focus exclusively on direct Bicep deployment to the dev environment.

## 🔍 Current State

✅ **Completed:**
- ADE deployment jobs (`deploy-ade-frontend`, `deploy-ade-backend`) are commented out
- Created reusable workflow `shared-infrastructure-deploy.yml` for Bicep deployment
- Added `deploy-dev-infrastructure` job using the reusable workflow

❌ **Issues Found:**
1. **Incorrect job structure**: `deploy-dev-infrastructure` job mixes job-level and step-level configuration
2. **Broken dependency**: `build-summary` job still references disabled ADE jobs in `needs`
3. **Unused artifacts**: Frontend artifacts are being downloaded but not used in infrastructure deployment
4. **Missing code deployment**: Infrastructure deployment doesn't include application code deployment

### 1. Fix CI Workflow Structure (`ci.yml`)

**Fix `deploy-dev-infrastructure` job:**
```yaml
deploy-dev-infrastructure:
  name: Deploy Dev Infrastructure
  needs: [bicep-validation]
  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  uses: ./.github/workflows/shared-infrastructure-deploy.yml
  with:
    environment: "dev"
    bicep-template: "infra/main-orchestrator.bicep"
    parameters-file: "infra/dev-orchestrator.parameters.bicepparam"
    location: "eastus2"
    validate-only: false
  secrets:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
```

**Update `build-summary` job dependencies:**
```yaml
build-summary:
  name: Build Summary
  runs-on: ubuntu-latest
  needs: [bicep-validation, frontend-build, backend-build, deploy-dev-infrastructure]
  if: always()
```

### 2. Add Application Deployment Jobs

Create separate jobs for deploying application code after infrastructure:

```yaml
deploy-dev-backend:
  name: Deploy Backend Code to Dev
  needs: [deploy-dev-infrastructure, backend-build]
  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download backend artifacts
      uses: actions/download-artifact@v4
      with:
        name: backend-publish
        path: ./backend-dist/
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Backend Function App
      run: |
        FUNCTION_APP_NAME="${{ needs.deploy-dev-infrastructure.outputs.backend-function-app-name }}"
        RESOURCE_GROUP="${{ needs.deploy-dev-infrastructure.outputs.backend-resource-group }}"
        
        echo "🚀 Deploying backend code to Function App: $FUNCTION_APP_NAME"
        az functionapp deployment source config-zip \
          --resource-group "$RESOURCE_GROUP" \
          --name "$FUNCTION_APP_NAME" \
          --src "./backend-dist/backend-publish.zip"

deploy-dev-frontend:
  name: Deploy Frontend Code to Dev
  needs: [deploy-dev-infrastructure, frontend-build]
  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download frontend artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist
        path: ./frontend-dist/
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Frontend Static Web App
      run: |
        STATIC_WEB_APP_NAME="${{ needs.deploy-dev-infrastructure.outputs.frontend-static-web-app-name }}"
        
        echo "🚀 Deploying frontend code to Static Web App: $STATIC_WEB_APP_NAME"
        # Use Azure/static-web-apps-deploy action or az swa deploy
```

### 3. Complete ADE Cleanup

**Remove all commented ADE code blocks:**
- Lines 54-69: `deploy-ade-frontend` job (commented)
- Lines 310-609: `deploy-ade-backend` job (commented)
- Any remaining ADE references in comments

**Update build summary to include new deployment jobs:**
```yaml
needs: [bicep-validation, frontend-build, backend-build, deploy-dev-infrastructure, deploy-dev-backend, deploy-dev-frontend]
```

### 4. Enhance Reusable Workflow

**Improve `shared-infrastructure-deploy.yml`:**
- Add better error handling for resource queries
- Include resource existence validation
- Add deployment status reporting
- Ensure all required outputs are captured

### 5. Update Documentation

**Files to update:**
- `.github/copilot-instructions.md`: Remove ADE references, add direct deployment guidance
- `documentation/CI_URL_RETRIEVAL_FIX.md`: Update with new approach
- `documentation/DEPLOYMENT_GUIDE.md`: Focus on Bicep + Azure CLI approach

## 🎯 Acceptance Criteria

✅ **Infrastructure Deployment:**
- [ ] `deploy-dev-infrastructure` job runs successfully
- [ ] All infrastructure resources are created in dev environment
- [ ] Infrastructure outputs are correctly captured and passed to dependent jobs

✅ **Application Deployment:**
- [ ] Backend Function App code deploys successfully
- [ ] Frontend Static Web App code deploys successfully
- [ ] Both applications are accessible and functional

✅ **CI/CD Pipeline:**
- [ ] Build summary job runs without errors
- [ ] All job dependencies are correct
- [ ] Pipeline completes successfully for main branch pushes

✅ **Code Quality:**
- [ ] All commented ADE code is removed
- [ ] No broken references to disabled jobs
- [ ] Clean, maintainable workflow structure

✅ **Documentation:**
- [ ] Updated documentation reflects new deployment approach
- [ ] Clear guidance for developers on the deployment process

## 🚀 Implementation Priority

1. **High Priority**: Fix CI workflow structure and dependencies
2. **High Priority**: Add application deployment jobs  
3. **Medium Priority**: Complete ADE code removal
4. **Medium Priority**: Enhance reusable workflow
5. **Low Priority**: Update documentation

## 🔗 Related Issues

- Issue #96: Python Foundry Agent implementation
- Previous work: ADE infrastructure setup and CI/CD implementation

## 📋 Implementation Notes

- **Testing**: Validate workflow changes in a feature branch before merging
- **Rollback Plan**: Keep current commented ADE code until new approach is proven
- **Monitoring**: Add deployment status reporting and error notification
- **Security**: Ensure Azure credentials and resource access are properly configured

---

**Assignee**: @copilot
**Labels**: ci/cd, infrastructure, azure-devops, high-priority
**Milestone**: Q1 2024 Infrastructure Modernization
