### ISSUE TITLE
Add Azure Deployment Environment (ADE) Integration to CI Pipeline

### ISSUE THREAD

**Issue by JFolberth** [JFolberth/ai-in-a-box#47]
### **Summary**
Implement ADE deployment as a separate CI job that deploys only the frontend infrastructure via ADE, then deploys the frontend code to the created infrastructure. This should run after frontend infrastructure validation and build checks pass.

#### **CI Job Structure**
- **Trigger**: After frontend infrastructure validation and build checks pass
- **Scope**: Frontend infrastructure ONLY (not backend)
- **Process**: 
  1. Create ADE environment using `az devcenter dev environment create`
  2. Extract outputs from ADE deployment
  3. Deploy frontend code to the newly created Static Web App

#### **ADE Configuration**
```yaml
DevCenterName: devecnter-eus-dev
DevCenterProjectName: ai-foundry  
DevCenterCatalogName: ai-in-abox-infrastructure
EnvironmentDefinitionName: AI_Foundry_SPA_Frontend
DevCenterProjectEnvironmentTypeName: ci
DeploymentEnvironmentInstanceName: aiab-ade
```

#### **Command Template**
```bash
az devcenter dev environment create \
  --dev-center-name "devecnter-eus-dev" \
  --project-name "ai-foundry" \
  --catalog-name "ai-in-abox-infrastructure" \
  --environment-definition-name "AI_Foundry_SPA_Frontend" \
  --environment-type "ci" \
  --name "aiab-ade" \
  --parameters @infra/environments/frontend/ade.parameters.json
```

#### **1. Create ADE Parameters File**
- **File**: `infra/environments/frontend/ade.parameters.json`
- **Exception**: This is the ONLY .json file allowed in infra (per project requirements)
- **Content**: Use default values from `infra/environments/frontend/main.bicep` for most parameters
- **Required Parameters**:
  ```json
  {
    "applicationName": { "value": "aibox" },
    "logAnalyticsWorkspaceName": { "value": "[TO_BE_PROVIDED]" },
    "logAnalyticsResourceGroupName": { "value": "[TO_BE_PROVIDED]" },
    "adeName": { "value": "aiab-ade" },
    "devCenterProjectName": { "value": "ai-foundry" }
  }
  ```

#### **2. Update CI Workflow**
- **File**: `.github/workflows/ci.yml`
- **New Job**: `deploy-ade-frontend`
- **Dependencies**: `[build-frontend, validate-frontend-infra]`
- **Steps**:
  1. Checkout code
  2. Azure CLI login
  3. Create ADE environment
  4. Extract outputs (Static Web App name, URL, etc.)
  5. Deploy frontend code to Static Web App
  6. Output deployment results

#### **3. ADE Job Implementation**
```yaml
deploy-ade-frontend:
  needs: [build-frontend, validate-frontend-infra]
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v4
    
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create ADE Environment
      id: create-ade
      run: |
        # Create ADE environment
        az devcenter dev environment create \
          --dev-center-name "devecnter-eus-dev" \
          --project-name "ai-foundry" \
          --catalog-name "ai-in-abox-infrastructure" \
          --environment-definition-name "AI_Foundry_SPA_Frontend" \
          --environment-type "ci" \
          --name "aiab-ade-${{ github.run_number }}" \
          --parameters @infra/environments/frontend/ade.parameters.json
        
        # Wait for deployment to complete
        # Extract outputs
        
    - name: Deploy Frontend Code
      run: |
        # Use deployment outputs to deploy frontend code
        # Deploy to Static Web App created by ADE
    
    - name: Cleanup ADE Environment
      if: always()
      run: |
        # Optional: Clean up ADE environment after testing
```

#### **4. Output Extraction Logic**
- Extract Static Web App name from ADE deployment
- Extract Static Web App URL for verification
- Extract deployment token for code deployment
- Store outputs as job outputs for potential reuse

#### **5. Frontend Code Deployment**
- Use existing deployment logic from `deploy-frontend-spa-code.ps1`
- Adapt for Static Web App created by ADE
- Ensure deployment uses extracted outputs, not hardcoded values

#### **Parameters Synchronization**
- **CRITICAL**: Ensure `ade.parameters.json` stays in sync with `infra/environments/frontend/main.bicep` parameters
- Add validation step to verify parameter compatibility
- Document parameter mapping in comments

#### **Naming Strategy**
- Use `aiab-ade-${github.run_number}` for unique environment names
- Avoid conflicts with existing environments
- Consider cleanup strategy for CI environments

#### **Error Handling**
- Handle ADE creation failures gracefully
- Implement retry logic for transient failures
- Ensure cleanup happens even on failures

#### **Security**
- Use appropriate service principal permissions for ADE operations
- Secure parameter files (avoid secrets in JSON)
- Use GitHub secrets for sensitive configuration

### **Acceptance Criteria**

- [ ] ADE parameters file created with all required parameters
- [ ] CI job runs after frontend validation passes
- [ ] ADE environment creates successfully
- [ ] Frontend code deploys to ADE-created infrastructure
- [ ] Deployment outputs are captured and logged
- [ ] Job handles failures gracefully with cleanup
- [ ] Documentation updated with ADE integration details
- [ ] No impact on existing deployment workflows

### **Files to Modify/Create**

1. **NEW**: `infra/environments/frontend/ade.parameters.json`
2. **MODIFY**: `.github/workflows/ci.yml`
3. **MODIFY**: `documentation/DEPLOYMENT_GUIDE.md` (add ADE section)
4. **MODIFY**: `README.md` (mention ADE testing capability)

### **Testing Strategy**

1. Test ADE creation with parameters file
2. Verify frontend deployment to ADE infrastructure
3. Test failure scenarios and cleanup
4. Validate no interference with existing CI jobs
5. Test parameter synchronization between Bicep and JSON

### **Dependencies**

- Azure DevCenter and Project must be properly configured
- Catalog must contain the AI_Foundry_SPA_Frontend definition
- Service principal needs DevCenter environment creation permissions
- Log Analytics workspace must exist and be accessible

---

**Priority**: High  
**Complexity**: Medium-High  
**Estimated Effort**: 2-3 days  

This implementation will provide automated testing of the frontend infrastructure via ADE while maintaining separation from the main deployment workflows.
