### ISSUE TITLE
ADE Backend Function App Deployment Failing - Missing .azurefunctions Directory

### ISSUE THREAD

**Issue by JFolberth** [JFolberth/ai-in-a-box#70]
# ADE Backend Function App Deployment Failing - Missing .azurefunctions Directory

## 🚨 Problem Description
ADE deployment of the backend Function App is failing with a package validation error. The deployment package is missing the required `.azurefunctions` directory at the root level.

## 💥 Error Details
```
InvalidPackageContentException: Package content validation failed: Cannot find required .azurefunctions directory at root level in the .zip package.
```

### Full Error Log
```json
[
  {"log_time":"2025-06-26T03:00:35.7543692Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"Starting deployment pipeline.","type":0},
  {"log_time":"2025-06-26T03:00:35.7706933Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"[Kudu-SourcePackageUriDownloadStep] Skipping download. Zip package is present at /tmp/zipdeploy/8f2346bb-7cd8-4014-9548-2a78d3e244e3.zip","type":0},
  {"log_time":"2025-06-26T03:00:35.7724569Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"[Kudu-ValidationStep] starting.","type":0},
  {"log_time":"2025-06-26T03:00:35.7915525Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"[Kudu-ValidationStep] completed.","type":0},
  {"log_time":"2025-06-26T03:00:35.7928596Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"[Kudu-ExtractZipStep] starting.","type":0},
  {"log_time":"2025-06-26T03:00:35.8334961Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"[Kudu-ExtractZipStep] completed.","type":0},
  {"log_time":"2025-06-26T03:00:35.8347347Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"[Kudu-ContentValidationStep] starting.","type":0},
  {"log_time":"2025-06-26T03:00:35.8381467Z","id":"8f2346bb-7cd8-4014-9548-2a78d3e244e3","message":"InvalidPackageContentException: Package content validation failed: Cannot find required .azurefunctions directory at root level in the .zip package.","type":2}
]
```

### Primary Suspect: GitHub Actions Build Process
The issue is likely in the GitHub Actions workflow that builds and packages the Function App for ADE deployment.

**Key files to investigate:**
- `.github/workflows/ci.yml` - Main CI pipeline
- `.github/workflows/shared-backend-build.yml` - Backend build workflow
- `src/backend/` - Function App source code structure

### Expected Function App Package Structure
A valid Azure Function App deployment package should contain:
```
deployment-package.zip
├── .azurefunctions/         ← MISSING - This is the problem!
├── host.json
├── local.settings.json (optional)
├── Function1/
│   ├── function.json
│   └── run.csx (or compiled binary)
├── bin/ (for compiled functions)
└── ... (other function directories)
```

### Step 1: Check Current GitHub Actions Build
**Files to examine:**
- `.github/workflows/shared-backend-build.yml`
- `.github/workflows/ci.yml` (backend build section)

**Questions to answer:**
- [ ] How is the Function App being built?
- [ ] What publish command is being used?
- [ ] Is the build output including the `.azurefunctions` directory?
- [ ] Are we using `dotnet publish` or `func pack`?

### Step 2: Verify Source Code Structure
**Files to check:**
- `src/backend/` directory structure
- `src/backend/host.json` exists
- `src/backend/.azurefunctions/` directory (should be generated during build)

### Step 3: Compare with Working Deployments
- [ ] Check if manual deployments work (using `deploy-backend-func-code.ps1`)
- [ ] Compare build artifacts between manual and CI builds
- [ ] Verify local development build produces correct structure

### Step 4: Fix Build Process
**Likely solutions:**
1. **Use `func pack` instead of `dotnet publish`**
2. **Ensure proper dotnet publish arguments** (e.g., `--output` directory)
3. **Add post-build step to create `.azurefunctions` directory**
4. **Update GitHub Actions to use Azure Functions Core Tools**

### Solution 1: Use Azure Functions Core Tools in CI
```yaml
# In GitHub Actions workflow
- name: Install Azure Functions Core Tools
  run: npm install -g azure-functions-core-tools@4

- name: Build and Package Function App
  run: |
    cd src/backend
    func pack --build-native-deps
```

### Solution 2: Fix dotnet publish Command
```yaml
# Ensure proper publish arguments
- name: Publish Function App
  run: |
    cd src/backend
    dotnet publish --configuration Release --output ./publish --runtime win-x64 --self-contained false
    # Create .azurefunctions directory if missing
    mkdir -p ./publish/.azurefunctions
```

### Solution 3: Post-Build Directory Creation
```yaml
# Add missing directory after build
- name: Create Azure Functions Directory
  run: |
    cd src/backend/publish
    mkdir -p .azurefunctions
    echo "Azure Functions deployment marker" > .azurefunctions/readme.txt
```

### Primary targets:
1. **`.github/workflows/shared-backend-build.yml`** - Fix backend build process
2. **`.github/workflows/ci.yml`** - Update ADE deployment section
3. **`src/backend/`** - Verify project structure

### Secondary files:
- `deploy-scripts/deploy-backend-func-code.ps1` - Ensure consistency
- Documentation for build process

### ✅ ADE Deployment Success
- [ ] Backend Function App deploys successfully via ADE
- [ ] Deployment package contains `.azurefunctions` directory
- [ ] Function endpoints are accessible after deployment
- [ ] AI Foundry integration works correctly

### ✅ CI/CD Process Fixed
- [ ] GitHub Actions build produces valid Function App package
- [ ] Build artifacts match manual deployment packages
- [ ] ADE deployment completes without package validation errors

### ✅ Documentation Updated
- [ ] Build process documented
- [ ] Troubleshooting guide for similar issues
- [ ] ADE deployment validation steps

## 🔗 Related Files
- `.github/workflows/shared-backend-build.yml`
- `.github/workflows/ci.yml`
- `src/backend/AIFoundryProxy.csproj`
- `src/backend/host.json`
- `deploy-scripts/deploy-backend-func-code.ps1`

## 🏷️ Priority
**High** - Blocking ADE backend deployments

## 👥 Assignee
@copilot - Focus on GitHub Actions build process investigation and fix
