### ISSUE TITLE
Implement Python Foundry Agent with Externalized Configuration and Prompt Management

### ISSUE THREAD

**Issue by JFolberth** [JFolberth/ai-in-a-box#96]
## 🎯 Objective

Implement a Python-based Foundry Agent under `src/agent/` that provides a flexible, configurable AI agent implementation with externalized configuration and prompt management.

### Core Functionality
- **Python-based agent**: Clean, maintainable Python implementation
- **AI Foundry integration**: Connect to AI Foundry endpoints using proper authentication
- **Conversation management**: Handle multi-turn conversations with thread persistence
- **Error handling**: Robust error handling and retry logic
- **Logging**: Comprehensive logging for debugging and monitoring

### Externalized Configuration
- **Configuration files**: YAML/JSON configuration files for agent settings
- **Environment variables**: Support for environment-based configuration overrides
- **Prompt templates**: External prompt files with template variable support
- **Model parameters**: Configurable model settings (temperature, max tokens, etc.)
- **Endpoint configuration**: Flexible endpoint and authentication configuration

### Agent Features
- **Multi-agent support**: Framework to support multiple agent personalities/roles
- **Plugin architecture**: Extensible plugin system for additional capabilities
- **Tool integration**: Support for function calling and tool integration
- **Streaming responses**: Support for streaming AI responses
- **Rate limiting**: Built-in rate limiting and quota management

## 🏗️ Proposed Structure

```
src/agent/
├── README.md                           # Agent documentation and setup
├── requirements.txt                    # Python dependencies
├── pyproject.toml                      # Modern Python project configuration
├── .env.example                        # Environment variables template
├── main.py                             # CLI entry point
├── agent/
│   ├── __init__.py
│   ├── core/
│   │   ├── __init__.py
│   │   ├── agent.py                    # Main agent class
│   │   ├── conversation.py             # Conversation management
│   │   ├── client.py                   # AI Foundry client wrapper
│   │   └── config.py                   # Configuration management
│   ├── prompts/
│   │   ├── __init__.py
│   │   ├── manager.py                  # Prompt template manager
│   │   ├── system/
│   │   │   ├── default.yaml            # Default system prompts
│   │   │   ├── assistant.yaml          # Assistant role prompts
│   │   │   └── specialist.yaml         # Specialist role prompts
│   │   └── templates/
│   │       ├── conversation.jinja2     # Conversation templates
│   │       ├── function_call.jinja2    # Function calling templates
│   │       └── error_handling.jinja2   # Error response templates
│   ├── plugins/
│   │   ├── __init__.py
│   │   ├── base.py                     # Base plugin class
│   │   ├── web_search.py               # Web search plugin example
│   │   └── file_operations.py          # File operations plugin example
│   └── utils/
│       ├── __init__.py
│       ├── logging.py                  # Logging configuration
│       ├── auth.py                     # Authentication utilities
│       └── rate_limit.py               # Rate limiting utilities
├── config/
│   ├── agent.yaml                      # Main agent configuration
│   ├── models.yaml                     # Model configuration
│   ├── endpoints.yaml                  # Endpoint configuration
│   └── environments/
│       ├── development.yaml            # Development overrides
│       ├── production.yaml             # Production overrides
│       └── testing.yaml                # Testing overrides
├── tests/
│   ├── __init__.py
│   ├── conftest.py                     # Pytest configuration
│   ├── test_agent.py                   # Agent core tests
│   ├── test_prompts.py                 # Prompt management tests
│   ├── test_plugins.py                 # Plugin system tests
│   └── fixtures/
│       ├── sample_config.yaml          # Test configuration
│       └── sample_prompts.yaml         # Test prompts
└── scripts/
    ├── setup.py                        # Setup and initialization
    ├── test_connection.py               # Connection testing
    └── deploy.py                        # Deployment utilities
```

### Configuration Management
```yaml
# config/agent.yaml example
agent:
  name: "AI Foundry Assistant"
  version: "1.0.0"
  description: "Intelligent assistant powered by AI Foundry"
  
model:
  name: "gpt-4o"
  temperature: 0.7
  max_tokens: 2048
  top_p: 0.9
  
conversation:
  max_history: 20
  persistence: true
  timeout: 300
  
features:
  streaming: true
  function_calling: true
  plugins_enabled: true
  
logging:
  level: "INFO"
  format: "structured"
  file: "logs/agent.log"
```

### Prompt Template System
```yaml
# prompts/system/default.yaml example
system_prompt: |
  You are {{ agent.name }}, an intelligent AI assistant.
  
  Your capabilities include:
  {% for capability in agent.capabilities %}
  - {{ capability }}
  {% endfor %}
  
  Guidelines:
  - Be helpful, harmless, and honest
  - Provide accurate information
  - Ask clarifying questions when needed
  
conversation_starter: |
  Hello! I'm {{ agent.name }}. How can I assist you today?
  
error_responses:
  network_error: "I'm experiencing connectivity issues. Please try again in a moment."
  rate_limit: "I'm currently handling many requests. Please wait a moment before trying again."
  general_error: "I encountered an error while processing your request. Let me try again."
```

### Agent Core Implementation
```python
# agent/core/agent.py example structure
from typing import Dict, List, Optional, AsyncGenerator
from .config import AgentConfig
from .client import AIFoundryClient
from .conversation import ConversationManager
from ..prompts.manager import PromptManager
from ..plugins.base import BasePlugin

class FoundryAgent:
    """Main Foundry Agent class with externalized configuration."""
    
    def __init__(self, config_path: str = "config/agent.yaml"):
        self.config = AgentConfig.load(config_path)
        self.client = AIFoundryClient(self.config.endpoint)
        self.conversation = ConversationManager(self.config.conversation)
        self.prompts = PromptManager(self.config.prompts_path)
        self.plugins: Dict[str, BasePlugin] = {}
        self._load_plugins()
    
    async def process_message(
        self, 
        message: str, 
        thread_id: Optional[str] = None,
        context: Optional[Dict] = None
    ) -> str:
        """Process a user message and return AI response."""
        pass
    
    async def stream_response(
        self, 
        message: str, 
        thread_id: Optional[str] = None
    ) -> AsyncGenerator[str, None]:
        """Stream AI response for real-time display."""
        pass
    
    def add_plugin(self, plugin: BasePlugin) -> None:
        """Add a plugin to extend agent capabilities."""
        pass
```

### Phase 1: Core Infrastructure
- [ ] Set up Python project structure and dependencies
- [ ] Implement configuration management system
- [ ] Create basic AI Foundry client wrapper
- [ ] Add logging and error handling framework
- [ ] Write initial tests for core components

### Phase 2: Agent Core
- [ ] Implement main Agent class
- [ ] Add conversation management with thread persistence
- [ ] Create prompt template system with Jinja2 support
- [ ] Implement streaming response capability
- [ ] Add comprehensive error handling and retry logic

### Phase 3: Plugin System
- [ ] Design and implement plugin architecture
- [ ] Create base plugin class and interface
- [ ] Implement sample plugins (web search, file operations)
- [ ] Add plugin discovery and loading system
- [ ] Create plugin documentation and examples

### Phase 4: Advanced Features
- [ ] Add function calling and tool integration
- [ ] Implement rate limiting and quota management
- [ ] Create deployment and monitoring scripts
- [ ] Add performance metrics and analytics
- [ ] Implement advanced conversation features

### Phase 5: Integration & Documentation
- [ ] Integrate with existing SPA frontend
- [ ] Create comprehensive documentation
- [ ] Add deployment guides and examples
- [ ] Implement CI/CD pipeline for agent
- [ ] Create usage examples and tutorials

### Frontend Integration
- **API endpoints**: RESTful API for frontend communication
- **WebSocket support**: Real-time streaming for chat interface
- **Authentication**: Integrate with existing auth system
- **Configuration UI**: Web interface for agent configuration

### Azure Integration
- **Function App hosting**: Deploy as Azure Function for serverless operation
- **Container Apps**: Alternative containerized deployment
- **Key Vault**: Secure configuration and secrets management
- **Application Insights**: Monitoring and telemetry

### Development Workflow
- **Local development**: Easy local setup and testing
- **Hot reload**: Configuration changes without restart
- **Debug mode**: Enhanced logging and debugging features
- **Testing framework**: Comprehensive unit and integration tests

### Core Dependencies
```
# Core AI and HTTP
openai>=1.0.0
httpx>=0.25.0
pydantic>=2.0.0

# Configuration and templating
pyyaml>=6.0
jinja2>=3.1.0
python-dotenv>=1.0.0

# Async and utilities
asyncio
aiofiles>=23.0.0
tenacity>=8.0.0

# Development and testing
pytest>=7.0.0
pytest-asyncio>=0.21.0
black>=23.0.0
ruff>=0.1.0
```

## 🎯 Success Criteria

- [ ] **Externalized configuration**: All agent behavior configurable via files
- [ ] **Prompt management**: Easy prompt editing without code changes
- [ ] **Plugin system**: Extensible architecture for new capabilities
- [ ] **Production ready**: Robust error handling, logging, and monitoring
- [ ] **Well documented**: Comprehensive docs for setup, usage, and extension
- [ ] **Test coverage**: >90% test coverage for core functionality
- [ ] **Performance**: Sub-second response times for standard queries
- [ ] **Integration**: Seamless integration with existing SPA application

## 📖 Documentation Requirements

- [ ] **README.md**: Setup, configuration, and usage guide
- [ ] **API documentation**: Detailed API reference
- [ ] **Plugin development**: Guide for creating custom plugins
- [ ] **Configuration reference**: Complete configuration options
- [ ] **Deployment guide**: Azure deployment instructions
- [ ] **Troubleshooting**: Common issues and solutions
- [ ] **Examples**: Real-world usage examples and tutorials

---

**Note**: This is a comprehensive implementation that will significantly enhance the AI Foundry SPA project with a flexible, maintainable Python agent system. The externalized configuration and prompt management will make it easy to customize agent behavior without code changes.

**Implementation can be assigned to GitHub Copilot by mentioning @copilot in a comment after issue creation.**
