### ISSUE TITLE
Disable ADE Deployment Steps and Focus on Dev Infrastructure Deployment

### ISSUE THREAD

**Issue by JFolberth** [JFolberth/ai-in-a-box#99]
## 🎯 Objective

Temporarily disable Azure Deployment Environment (ADE) deployment steps in CI/CD pipeline and focus on direct infrastructure deployment to dev environment using existing Bicep orchestrator.

## 📋 Current Situation

- **ADE deployment complexity**: Current CI/CD includes complex ADE environment creation and resource extraction
- **Development focus needed**: Need to prioritize stable dev environment deployment
- **Infrastructure first approach**: Deploy infrastructure before focusing on application deployment complexities

### 1. **Disable ADE Deployment Jobs**
- [ ] Comment out or disable `deploy-ade-frontend` job in CI workflow
- [ ] Comment out or disable `deploy-ade-backend` job in CI workflow
- [ ] Keep build and validation steps active
- [ ] Maintain artifact generation for future use

### 2. **Create Dev Infrastructure Deployment Workflow**
- [ ] Create reusable workflow for infrastructure deployment
- [ ] Use existing `dev-orchestrator.parameters.bicepparam` configuration
- [ ] Deploy to dev environment using standard Azure CLI + Bicep
- [ ] Focus on infrastructure-only deployment initially

### 3. **Reusable Workflow Architecture**
- [ ] Create shared workflow templates in `.github/workflows/shared-*`
- [ ] Infrastructure deployment workflow (reusable)
- [ ] Application deployment workflow (future)
- [ ] Environment-specific parameter handling

### 4. **Dev Environment Priority**
- [ ] Use existing dev configuration parameters
- [ ] Deploy to standard resource groups (not ADE-generated names)
- [ ] Validate infrastructure deployment before application deployment

### **Phase 1: Disable ADE (Immediate)**
```yaml
# In ci.yml - Comment out ADE jobs
# deploy-ade-frontend:
#   name: Deploy ADE Frontend
#   runs-on: ubuntu-latest
#   # ... (commented out)

# deploy-ade-backend:  
#   name: Deploy ADE Backend
#   runs-on: ubuntu-latest
#   # ... (commented out)
```

### **Phase 2: Create Reusable Infrastructure Workflow**
```yaml
# .github/workflows/shared-infrastructure-deploy.yml
name: 'Shared: Infrastructure Deployment'
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      bicep-template:
        required: true
        type: string
      parameters-file:
        required: true
        type: string
      location:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
```

### **Phase 3: Dev Environment Deployment**
```yaml
# New job in ci.yml for dev infrastructure
deploy-dev-infrastructure:
  name: Deploy Dev Infrastructure
  uses: ./.github/workflows/shared-infrastructure-deploy.yml
  with:
    environment: "dev"
    bicep-template: "infra/main-orchestrator.bicep"
    parameters-file: "infra/dev-orchestrator.parameters.bicepparam"
    location: "eastus2"
  secrets:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
```

### **Infrastructure Deployment**
- [ ] **Successful deployment** to dev environment using existing parameters
- [ ] **Resource groups created** with proper naming convention
- [ ] **Application Insights** deployed and configured
- [ ] **Function App** infrastructure ready for code deployment
- [ ] **Static Web App** infrastructure ready for frontend deployment

### **CI/CD Pipeline**
- [ ] **Build and validation** jobs continue to work
- [ ] **ADE deployment disabled** without breaking pipeline
- [ ] **Reusable workflows** created for future environments
- [ ] **Artifact generation** maintained for deployment steps

### **Development Workflow**
- [ ] **Local development** unaffected by CI changes
- [ ] **Manual deployment scripts** continue to work
- [ ] **Infrastructure outputs** available for application deployment
- [ ] **Environment variables** properly configured

### **Existing Files (No Changes Needed)**
- `infra/main-orchestrator.bicep` - Main infrastructure template
- `infra/dev-orchestrator.parameters.bicepparam` - Dev environment parameters
- `deploy-scripts/deploy.ps1` - Manual deployment option
- `deploy-scripts/deploy.sh` - Cross-platform deployment

### **Expected Resource Creation**
Based on `dev-orchestrator.parameters.bicepparam`:
- **Location**: eastus2
- **Frontend RG**: `rg-ai-foundry-spa-frontend-dev-eus2`
- **Backend RG**: `rg-ai-foundry-spa-backend-dev-eus2`
- **AI Foundry**: `cs-ai-foundry-dev-eus2` (existing)
- **Log Analytics**: `la-logging-dev-eus` (existing)

## 🔗 Related Files

- `.github/workflows/ci.yml` - Main CI workflow to modify
- `infra/dev-orchestrator.parameters.bicepparam` - Dev environment config
- `.github/workflows/shared-*` - Reusable workflow templates (to create)

## 🏷️ Labels
- `ci-cd`
- `infrastructure`
- `azure-bicep`
- `dev-environment`
- `workflow-improvement`

## 👥 Assignees
This can be implemented incrementally:
1. **Disable ADE steps** (quick fix)
2. **Create reusable workflows** (architecture improvement)
3. **Deploy dev infrastructure** (validation)

---

**Priority**: High - This will simplify the development workflow and provide a stable foundation for infrastructure deployment before tackling more complex ADE scenarios.
